### ISSUE TITLE
Trezor T is not supported

### ISSUE THREAD

**Issue by xaionaro** [conejoninja/tesoro#7]
```
~/go/src/github.com/conejoninja/tesoro/example$ go run main.go 
No TREZOR devices found, make sure your device is connected
```

**Comment by conejoninja** [comment]
You are right, it's not compatible. The new communication protocol is _a bit_ different from model One, it will take a considerable amount of time to make it work. I will leave this open, but don't have much time lately to add this.

**Comment by rfjakob** [comment]
Hmm, this is strange, check this out: https://github.com/trezor/trezor-core/issues/91#issuecomment-355759065

> T2 supports v1 protocol.

I'll create a ticket over there asking about the status.

**Comment by conejoninja** [comment]
This commits ( https://github.com/conejoninja/tesoro/commit/1ec64ae38f9bd52e03b956765c9e905bbd8768f9 ) adds the vendor information so it's recognized by the example. One odd thing is that in my computer only shows the interface 1, and I think it should be the 0

**Comment by rfjakob** [comment]
Thanks, I also tried that ( https://github.com/rfjakob/tesoro/commit/0e43b88184b3f5648e4cb9d3d5a14e45ebe01926 ). It seems to hang at some point:
```
~/go/src/github.com/conejoninja/tesoro/example$ ./example 
Found 1 TREZOR devices connected
>init
^C
```
I have asked at https://github.com/trezor/trezor-core/issues/254 about the status of protocol version 1 support in the Model T.

**Comment by rfjakob** [comment]
Got the answer https://github.com/trezor/trezor-core/issues/254#issuecomment-401215063 :

> Trezor T talks only over WebUSB, and its HID interface is reserved for U2F.
> Other than that, it speaks unmodified v1 protocol.

The HID interface is only for U2F!

**Comment by conejoninja** [comment]
I hacked something together and modelT is kind of _working_ (hardcoded vendor info, so One is not working ) check the _modelT_ branch : https://github.com/conejoninja/tesoro/tree/modelT

I *need* to clean the code, there's also *cerrojo* ( https://github.com/conejoninja/cerrojo ) which is the same as *tesoro* but _updated_ a little bit and compatible with keepkey wallets. Both of them needs some updates (which I do not have time to) since I didn't update the protobuf messages for a while.

I left this open since there's lot of work to do:
- Update protobuffer files
- Clean code
- Port HIDAPI transport from cerrojo to tesoro
- Extend transports to include Enumerate/Connect (take code from main to each transport)
- Dep
- Check functions (sethomescreen) that are unique for each device


*WARNING:* Some functions may not work in the current state, for example "getfeatures" since the protobuffer message has been updated to include more information, it will fail.

**Comment by rfjakob** [comment]
Wow, awesome!

About cerrojo vs tesoro: Do you want do merge the two and only keep cerrojo? I could maybe find time to work on the open issues, and merge both libraries.

**Comment by conejoninja** [comment]
That was the original idea, but I think trezor and keepkey have diverted a little too much to be worth it. I'll try to clean/update _tesoro_, if it's not done in a couple of days, remember me or feel free to send some PRs.

**Comment by rfjakob** [comment]
Ok, sounds good!

**Comment by conejoninja** [comment]
- Update protobuffer files ✔️
- Clean code ✔️
- Port HIDAPI transport from cerrojo to tesoro ❌ conflicts with the hidapi libs used in webusb
- Extend transports to include Enumerate/Connect (take code from main to each transport) ❌ not yet, need to think a bit more about it. We could use the implementations at trezord-go/usb , or even talk directly with trezor bridge, it will be less work in the future, but I like the idea of a different implementation (for security/redundancy/privacy/...) 
- Dep ✔️
- Check functions (sethomescreen) that are unique for each device ❌ didn't have the time yet, supported functions/messages not completed, WIP



Changes in:
https://github.com/conejoninja/tesoro/pull/8
https://github.com/conejoninja/tesoro/commit/a882d578178809887f61607fc5625c4769511cfc


I consider most of the work done and cleaned it a little bit. New messages are still a work in progress (help welcome).
